language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
   - "if [[ $DJANGO == '1.5.x' ]]; then pip install https://github.com/django/django/archive/stable/1.5.x.zip#egg=Django; else pip install Django==$DJANGO --use-mirrors; fi"
   - pip install -r requirements-dev.txt --use-mirrors
   - python setup.py develop
env:
  - DJANGO="1.3.3"
  - DJANGO="1.4.1"
  - DJANGO="1.5.x"
script: python setup.py test
matrix:
    exclude:
       - python: "2.5"
         env: DJANGO="1.5.x"
