language: python
python:
  - "2.6"
  - "2.7"
install:
   - pip install Django==$DJANGO --use-mirrors
   - pip install -r requirements-dev.txt --use-mirrors
   - python setup.py develop
env:
  - DJANGO="1.3.7"
  - DJANGO="1.4.5"
  - DJANGO="1.5.0"
script: python setup.py nosetests

